# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0749c583fcce427b3d69904eae7068c634a6fefb30f3ed76676a0399d39ba8a330ba95434ffbd8033de150bc24e51d7ec9a35941518293a6432ecd86f60ff795

test:
  secret_key_base: 085800135508d0ed0739b5bfbec7e48fea6ba0d8efef0ebe30b5155c1e24d2f3f1bf10db37bbec7ef0c533716091a29a7ba91f980829fe734bada7739b1044fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
